erblint:
  config_file: .erb-lint.yml
  enabled: true

eslint:
  enabled: true
  ignore_file: .eslintignore

flake8:
  enabled: true

flog:
  enabled: true

phpcs:
  enabled: true

reek:
  enabled: true
  config_file: .reek.yml

rubocop:
  enabled: false

shellcheck:
  enabled: true
