AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.7.2

### LAYOUT
Layout/EndOfLine:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DuplicateBranch:
  Enabled: false

Style/StringLiterals:
  Enabled: true

### METRICS
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 44

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 130

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

### STYLING
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/Semicolon:
  Enabled: true
