language: python

sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

install: "pip install -r requirements.txt"

script:
  - pylint --version
  - find . -name "*.py" | xargs pylint --disable=C0103,C0114
  - flake8 --version
  - flake8 --ignore=E501

branches:
  only:
    - master
