language: python

sudo: false

python:
  - "3.6"
  - "3.7"
  - "nightly"

install: "pip install defusedxml flake8 lxml pylint requests yamllint"

script:
  - pylint --version
  - find . -name "*.py" | xargs pylint --disable=C0103
  - flake8 --version
  - flake8 --ignore=E501

branches:
  only:
    - master
