# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  ruby:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.4-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: 🏗️ Install dependencies
          command: |
            gem install bundler
            bundle update --bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: 🧹 Run Ruby lint
          command: |
            bundle exec rubocop
      - run:
          name: 🧹 Run Markdown lint
          command: |
            bundle exec mdl .
      - run:
          name: 🧹 Run percy snapshots
          command: |
            cd docs
            bundle exec jekyll build
            npx percy snapshot _site/ --ignore-files "assets/python/**,parallel-universe/index.html"

  python:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.5-buster-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 🏗️ Install dependencies
          command: |
            sudo apt update
            sudo pip install defusedxml flake8 lxml pylint requests yamllint
      - run:
          name: 🧹 Run YAML lint
          command: |
            yamllint .
      - run:
          name: 🧹 Run Pylint
          command: |
            find . -name "*.py" | xargs pylint --disable=C0103
      - run:
          name: 🧹 Run Flake8
          command: |
            flake8 --ignore=E501

  surge:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.5-buster-node-browsers
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: ✉️ Surge Deployment
          command: |
            './node_modules/.bin/surge --project ./govegas --domain https://govegas.surge.sh/'

  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:v0.4.6
    steps:
      - checkout
      - run:
          name: 🧹 Lint shell scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources

  go-lint:
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.13.3 #
    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/fuchsia-programming/fuchsia
    steps:
      - checkout
      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
      - run: go get -u github.com/mgechev/revive
      - run:
          name: 🧹 Run Golang revive lint
          command: |
            cd scrapers/go
            sh ./check-revive.sh || exit 1
      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  shell:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: 🐚 Print quotes from Brainyquote using shell
          command: |
            cd scrapers/shell
            sh ./brainyquote.sh tennis balls
      - run:
          name: 🐚 Print the maximum number of contributions in the last year from a users GitHub profile using sed
          command: |
            cd scrapers/shell
            sh ./github-max-per-day-sed.sh fabpot
      - run:
          name: 🐚 Print the maximum number of contributions in the last year from a users GitHub profile using pcregrep
          command: |
            cd scrapers/shell
            sh ./github-max-per-day-pcregrep.sh fabpot
      - run:
          name: 🐚 Print the maximum number of contributions in the last year from a users GitHub profile using perl
          command: |
            cd scrapers/shell
            sh ./github-max-per-day-perl.sh fabpot
      - run:
          name: 🐚 Print the maximum number of contributions in the last year from a users GitHub profile using awk
          command: |
            cd scrapers/shell
            sh ./github-max-per-day-awk.sh fabpot

workflows:
  version: 2
  build:
    jobs:
      - ruby
      - python
      - shellcheck
      - go-lint
      - shell:
          requires:
            - ruby
            - python
            - shellcheck
            - go-lint
      - surge:
          filters:
            branches:
              only: master
